name: 'Merge PR from Release to Develop'
on:
  # Allow manual triggering: This requires you to choose a `ref`. This should be the branch with changes
  workflow_dispatch:
  # run 0:00 UTC every day
  schedule:
    - cron: '0 0 * * *'

jobs:
  forward-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - uses: NicholasBoll/action-forward-merge-pr@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branches: release+develop
          prefix: 'chore: '
